version: '3.5'
version: '3.10'
services:
  web:
    build: .
    ports: 
    - "8000:8000"
    container_name: martor_demo
    restart: unless-stopped
    container_name: app
    restart: unless-stopped
